sut:
  build: .
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    MONGO_TEST_DB_NAME: ${MONGO_TEST_DB_NAME}
    WAIT_HOSTS: mongo:27017
  ports:
    - ${PORT}:${PORT}
    - 9229:9229
  command: npm test
