version: '2.1'

services:
  beautipi:
    image: beautipi
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
      - 9229:9229
    command: node --inspect app.js
    links:
      - mongo
  mongo:
    image: mongo
    ports:
    - 27017:27017
