version: '2.1'

services:
  beautipi:
    image: beautipi
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8888:8888
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
