version: '2.1'

services:
  beautipi:
    image: beautipi
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongo:27017
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: node --inspect app.js
  mongo:
    image: mongo
    env_file:
      - .env
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
